force-app/main/default/objects/GitHub_Repository__x/GitHub_Repository__x.object-meta.xml
<CustomObject>
    <description>GitHub Repository</description>
    <externalDataSource>GitHub_Data_Source</externalDataSource>
    <externalName>GitHub Repository</externalName>
    <label>GitHub Repository</label>
    <pluralLabel>GitHub Repositories</pluralLabel>
</CustomObject>

force-app/main/default/objects/GitHub_Repository__x/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description</description>
    <externalDeveloperName>Description</externalDeveloperName>
    <label>Description</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GitHub_Repository__x/fields/LastPushedDate__c.field-meta.xml
<CustomField>
    <fullName>LastPushedDate__c</fullName>
    <description>Last Pushed Date</description>
    <externalDeveloperName>LastPushedDate</externalDeveloperName>
    <label>Last Pushed Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GitHub_Repository__x/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <description>Size</description>
    <externalDeveloperName>Size</externalDeveloperName>
    <label>Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GitHub_Repository__x/fields/Stars__c.field-meta.xml
<CustomField>
    <fullName>Stars__c</fullName>
    <description>Stars</description>
    <externalDeveloperName>Stars</externalDeveloperName>
    <label>Stars</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GitHub_Repository__x/fields/TotalForks__c.field-meta.xml
<CustomField>
    <fullName>TotalForks__c</fullName>
    <description>Total Forks</description>
    <externalDeveloperName>TotalForks</externalDeveloperName>
    <label>Total Forks</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GitHubRepoController.cls
public with sharing class GitHubRepoController {
    @AuraEnabled(cacheable=true)
    public static List<GitHub_Repository__x> fetchGitHubRepos() {
        
        List<GitHub_Repository__x> repoList = [
            SELECT Id, 
            DisplayUrl,
            Name__c,
            Description__c,
            RepoCreatedDate__c,
            RepoUpdatedDate__c,
            LastPushedDate__c,
            Language__c,
            OpenIssuesCount__c,
            Private__c,
            TotalForks__c,
            Stars__c,
            Size__c            
               from GitHub_Repository__x 
               ORDER BY LastPushedDate__c DESC
                LIMIT 1000];
        
        return repoList;
    }
}